mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /study
spring:
    application:
        name: study
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: 1234
        url: jdbc:oracle:thin:@//43.202.165.0:1522/XEPDB1
        username: mjlee
    devtools:
        livereload:
            enabled: true
